# Generated by Django 4.1.5 on 2023-01-09 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0003_department_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='cert',
            field=models.CharField(default='B.Eng', max_length=10),
            preserve_default=False,
        ),
    ]
