# Generated by Django 3.2.6 on 2023-01-10 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0005_level_semester'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='level',
            options={'ordering': ['level']},
        ),
        migrations.AlterModelOptions(
            name='semester',
            options={'ordering': ['semester']},
        ),
    ]
