# Generated by Django 3.2.6 on 2023-01-10 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0007_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lock_reason',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
