# Generated by Django 4.1.5 on 2023-01-11 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0008_user_lock_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='max_level',
            field=models.IntegerField(default=400),
        ),
    ]
