# Generated by Django 4.1.5 on 2023-01-11 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0009_department_max_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='number_of_years',
            field=models.IntegerField(default=4),
        ),
    ]
