# Generated by Django 4.1.5 on 2023-01-30 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0011_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='defer',
            field=models.BooleanField(default=False),
        ),
    ]
