# Generated by Django 4.1.5 on 2023-01-31 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0012_user_defer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(blank=True, max_length=100, null=True)),
                ('school_initial', models.CharField(blank=True, max_length=5, null=True)),
                ('school_domain_name', models.CharField(blank=True, max_length=255, null=True)),
                ('school_logo', models.ImageField(blank=True, null=True, upload_to='configuration')),
            ],
        ),
    ]
