# Generated by Django 4.1.5 on 2023-02-04 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0014_certification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name']},
        ),
    ]
