# Generated by Django 4.1.5 on 2023-02-04 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0015_alter_department_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='course_reg_status',
            field=models.BooleanField(default=False),
        ),
    ]
