# Generated by Django 4.1.5 on 2023-02-04 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0016_config_course_reg_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='course_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='config',
            name='course_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
