# Generated by Django 4.1.5 on 2023-02-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0017_config_course_end_date_config_course_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_reset',
            field=models.BooleanField(default=False),
        ),
    ]
