# Generated by Django 4.1.5 on 2023-02-09 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0018_user_password_reset'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='dept_abbr',
            field=models.CharField(default='csc', max_length=5),
            preserve_default=False,
        ),
    ]
