# Generated by Django 4.1.5 on 2023-01-15 21:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_setup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(max_length=150)),
                ('amount', models.IntegerField()),
                ('level', models.CharField(max_length=100)),
                ('ref', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
    ]
