# Generated by Django 4.1.5 on 2023-01-16 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='semester',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='session',
            field=models.CharField(default='2021/2022', max_length=20),
            preserve_default=False,
        ),
    ]
