# Generated by Django 4.1.5 on 2023-01-16 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0010_department_number_of_years'),
        ('payment', '0005_alter_payment_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.semester'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.session'),
        ),
    ]
