# Generated by Django 4.1.5 on 2023-01-28 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_alter_payment_semester_alter_payment_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_setup',
            name='category',
            field=models.CharField(default='tuition', max_length=100),
            preserve_default=False,
        ),
    ]
