# Generated by Django 4.1.5 on 2023-01-28 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_payment_setup_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='category',
            field=models.CharField(default='tuition', max_length=100),
            preserve_default=False,
        ),
    ]
