# Generated by Django 4.1.5 on 2023-02-09 03:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_payment_setup_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_setup',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
