# Generated by Django 4.1.5 on 2023-02-09 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0012_payment_setup_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='complete',
            field=models.BooleanField(default=True),
        ),
    ]
