# Generated by Django 3.2.6 on 2023-01-10 08:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuration', '0007_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=20)),
                ('course_title', models.CharField(max_length=200)),
                ('credit_unit', models.IntegerField()),
                ('level', models.CharField(max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('coodinator', models.CharField(blank=True, max_length=100, null=True)),
                ('ref', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.department')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.semester')),
            ],
        ),
        migrations.CreateModel(
            name='Registered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(max_length=100)),
                ('lock', models.BooleanField(default=False)),
                ('ref', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courses')),
                ('semester_registered', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.semester')),
                ('session_registered', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.session')),
            ],
        ),
    ]
