# Generated by Django 4.1.5 on 2023-01-12 21:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0010_department_number_of_years'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='department_setup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=20)),
                ('max_credit_unit', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.department')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.semester')),
            ],
        ),
    ]
