# Generated by Django 4.1.5 on 2023-01-12 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_registered_credit_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registered',
            name='credit_unit',
            field=models.IntegerField(editable=False),
        ),
    ]
