# Generated by Django 4.1.5 on 2023-02-02 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_registered_credit_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='registered',
            name='start_reg',
            field=models.BooleanField(default=False),
        ),
    ]
