# Generated by Django 4.1.5 on 2023-02-02 01:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0013_config'),
        ('student', '0002_alter_student_level'),
        ('courses', '0006_registered_start_reg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registered',
            name='start_reg',
        ),
        migrations.CreateModel(
            name='Donecourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_reg', models.BooleanField(default=False)),
                ('level', models.IntegerField(default=100)),
                ('date_started', models.DateTimeField(default=django.utils.timezone.now)),
                ('printed_on', models.DateTimeField(blank=True, null=True)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.semester')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
