# Generated by Django 4.1.5 on 2023-02-02 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_remove_registered_start_reg_donecourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donecourse',
            name='level',
            field=models.IntegerField(),
        ),
    ]
