# Generated by Django 4.1.5 on 2023-02-02 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_donecourse_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donecourse',
            old_name='start_reg',
            new_name='status',
        ),
    ]
