# Generated by Django 4.1.5 on 2023-02-02 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_rename_start_reg_donecourse_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donecourse',
            old_name='printed_on',
            new_name='registered_on',
        ),
    ]
