# Generated by Django 4.1.5 on 2023-02-02 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_rename_printed_on_donecourse_registered_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department_setup',
            name='semester',
            field=models.CharField(max_length=5),
        ),
    ]
