# Generated by Django 4.1.5 on 2023-02-02 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_alter_department_setup_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='semester',
            field=models.CharField(max_length=10),
        ),
    ]
