# Generated by Django 4.1.5 on 2023-02-04 08:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_alter_courses_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='department_setup',
            name='ref',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
