# Generated by Django 4.1.5 on 2023-02-09 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_department_setup_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='core_course',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
