# Generated by Django 4.1.5 on 2023-01-09 13:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jamb_number', models.CharField(max_length=50)),
                ('registration_num', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('other_name', models.CharField(max_length=100)),
                ('entry_mode', models.CharField(max_length=20)),
                ('level', models.IntegerField(default=1)),
                ('entry_session', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('sex', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('lock', models.BooleanField(default=False)),
                ('ref', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.department')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.faculty')),
            ],
        ),
    ]
