# Generated by Django 4.1.5 on 2023-02-14 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_student_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='passport',
            field=models.ImageField(default='passport.jpg', upload_to='Student'),
        ),
    ]
