# Generated by Django 4.1.5 on 2023-01-29 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='occupant',
            old_name='term',
            new_name='semester',
        ),
    ]
