# Generated by Django 4.1.5 on 2023-02-13 01:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment', '0013_payment_complete'),
        ('configuration', '0019_department_dept_abbr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=20)),
                ('other_name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('jamb', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=20)),
                ('ref', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_num', models.CharField(max_length=100)),
                ('cleared', models.BooleanField(default=False)),
                ('admitted', models.BooleanField(default=False)),
                ('ref', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.applicant')),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=20)),
                ('other_name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=20)),
                ('jamb', models.CharField(max_length=20)),
                ('address', models.TextField(max_length=200)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('photo', models.ImageField(default='passport.jpg', upload_to='Application')),
                ('ref', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.applicant')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rrr', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('order_id', models.CharField(max_length=1000)),
                ('ref', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('generated_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('paid_on', models.DateTimeField(blank=True, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.applicant')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicant_payment', to='payment.payment_setup')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicant_payment_session', to='configuration.session')),
            ],
        ),
        migrations.CreateModel(
            name='Olevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(max_length=100)),
                ('exam_number', models.CharField(blank=True, max_length=100, null=True)),
                ('exam_year', models.CharField(max_length=20)),
                ('exam_center', models.CharField(max_length=20)),
                ('sub1', models.CharField(max_length=50)),
                ('grade1', models.CharField(max_length=5)),
                ('sub2', models.CharField(max_length=50)),
                ('grade2', models.CharField(max_length=5)),
                ('sub3', models.CharField(max_length=50)),
                ('grade3', models.CharField(max_length=5)),
                ('sub4', models.CharField(max_length=50)),
                ('grade4', models.CharField(max_length=5)),
                ('sub5', models.CharField(max_length=50)),
                ('grade5', models.CharField(max_length=5)),
                ('sub6', models.CharField(max_length=50)),
                ('grade6', models.CharField(max_length=5)),
                ('sub7', models.CharField(max_length=50)),
                ('grade7', models.CharField(max_length=5)),
                ('sub8', models.CharField(max_length=50)),
                ('grade8', models.CharField(max_length=5)),
                ('sub9', models.CharField(max_length=50)),
                ('grade9', models.CharField(max_length=5)),
                ('ref', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.applicant')),
            ],
        ),
        migrations.CreateModel(
            name='NOK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile', models.CharField(max_length=20)),
                ('relationship', models.CharField(max_length=20)),
                ('address', models.TextField(max_length=200)),
                ('gender', models.CharField(max_length=10)),
                ('ref', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.applicant')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.applicant')),
                ('dept1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicat_first_choice', to='configuration.department')),
                ('dept2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicat_second_choice', to='configuration.department')),
            ],
        ),
        migrations.CreateModel(
            name='Admitted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.applicant')),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.department')),
            ],
        ),
        migrations.CreateModel(
            name='Acceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rrr', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('order_id', models.CharField(max_length=1000)),
                ('ref', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('generated_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('paid_on', models.DateTimeField(blank=True, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.applicant')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.payment_setup')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.session')),
            ],
        ),
    ]
