# Generated by Django 4.1.5 on 2023-02-13 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_student_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='other_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
