# Generated by Django 4.1.5 on 2023-02-13 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_alter_personal_other_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='session',
        ),
        migrations.AlterField(
            model_name='personal',
            name='address',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='personal',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personal',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
