# Generated by Django 4.1.5 on 2023-02-13 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_remove_payment_session_alter_personal_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.IntegerField(default=30900),
            preserve_default=False,
        ),
    ]
