# Generated by Django 4.1.5 on 2023-02-13 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_payment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='session',
            field=models.CharField(default='2021/2022', max_length=20),
            preserve_default=False,
        ),
    ]
