# Generated by Django 4.1.5 on 2023-02-13 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_payment_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='admitted',
            name='session',
            field=models.CharField(default='2021/2022', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicant',
            name='session',
            field=models.CharField(default='2021/2022', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='session',
            field=models.CharField(default='2021/2022', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nok',
            name='session',
            field=models.CharField(default='2021/2022', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='olevel',
            name='session',
            field=models.CharField(default='2021/2022', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personal',
            name='session',
            field=models.CharField(default='2021/2022', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='session',
            field=models.CharField(default='2021/2022', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='acceptance',
            name='session',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='registration_num',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
