# Generated by Django 4.1.5 on 2023-02-13 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_alter_nok_address_alter_nok_full_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nok',
            name='gender',
        ),
    ]
