# Generated by Django 4.1.5 on 2023-02-13 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_olevel_exam_center2_olevel_exam_number2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='olevel',
            name='sub52',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
