# Generated by Django 4.1.5 on 2023-02-13 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_student_course_student_olevel_student_pesonal'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='nok',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.nok'),
        ),
    ]
