# Generated by Django 4.1.5 on 2023-02-13 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0013_student_nok'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='pesonal',
            new_name='personal',
        ),
    ]
