# Generated by Django 4.1.5 on 2023-02-14 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0014_rename_pesonal_student_personal'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptance',
            name='amount',
            field=models.IntegerField(default=12345),
            preserve_default=False,
        ),
    ]
