# Generated by Django 4.1.5 on 2023-02-14 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0015_acceptance_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olevel1', models.ImageField(upload_to='Document')),
                ('olevel2', models.ImageField(blank=True, null=True, upload_to='Document')),
                ('birth', models.ImageField(upload_to='Document')),
                ('lga', models.ImageField(upload_to='Document')),
                ('jamb_result', models.ImageField(upload_to='Document')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.applicant')),
            ],
        ),
    ]
